name: Revert to Previous Commit

on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Revert to specific commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git revert --no-commit ${{ github.sha }}..b80d562a19dbb22fd97bda42d50bfaa0628019ea
          git commit -m "Revert to commit b80d562a19dbb22fd97bda42d50bfaa0628019ea"
          git push
